sudo: required
services:
  - docker

before_install:
  - docker build -t nitesh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nitesh/react-test npm test

after_success:
  - docker build -t nitesh/multi-client ./client
  - docker build -t nitesh/multi-server ./server
  - docker build -t nitesh/multi-nginx ./nginx
  - docker build -t nitesh/multi-worker ./worker
  # Take those images and push to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nitesh/multi-client
  - docker push nitesh/multi-server
  - docker push nitesh/multi-nginx
  - docker push nitesh/multi-worker
