sudo: required
services:
  - docker

before_install:
  - docker build -t niteshldd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run niteshldd/react-test npm test

after_success:
  - docker build -t niteshldd/multi-client ./client
  - docker build -t niteshldd/multi-server ./server
  - docker build -t niteshldd/multi-nginx ./nginx
  - docker build -t niteshldd/multi-worker ./worker
  # Take those images and push to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push niteshldd/multi-client
  - docker push niteshldd/multi-server
  - docker push niteshldd/multi-nginx
  - docker push niteshldd/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: mult_docker
  env: MultDocker-env
  bucket_name: elasticbeanstalk-us-west-2-409888909294
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  
