version: '3'
services:
   postgres:
     image: 'postgres:latest'
   redis:
     image: 'redis:latest'
   nginx:
     restart: always
     build:
       dockerfile: Dockerfile.dev
       context: ./nginx
     ports:
       - '3050:80'
   api:
     build:
       dockerfile: Dockerfile.dev
       context: ./server
       #specify the file to copy
     volumes:
       - /app/node_modules
       #not change the file 
       - ./server:/app
       #for all the expect node_module look for above steps
       #variableName=value - inside the container at run time set the envoiroment
       #variableName -Sets a variable in the container run time - value is taken from your computer
     environment:
       - REDIS_HOST=redis
       - REDIS_PORT=6379
       - PGUSER=postgres
       - PGHOST=postgres
       - PGDATABASE=postgres
       - PGPASSWORD=postgres_password
       - PGPORT=5432
   client:
     build:
       dockerfile: Dockerfile.dev
       context: ./client
     volumes:
       - /app/node_modules
       - ./client:/app
   worker:
     build:
       dockerfile: Dockerfile.dev
       context: ./worker
     volumes:
       - /app/node_modules
       - ./worker:/app
     environment:
       - REDIS_HOST=redis
       - REDIS_PORT=6379
      
